<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19.03.2018
 * Time: 22:39
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created at' => 'Створено',
    'Updated at' => 'Оновлено',
    'Announce' => 'Анонс',
    'Are you sure you want to delete this item?' => 'Ви бажаєте вилучити цей запис?',
    'Audio Notepad'=> 'Аудіо Блокнот',
    'Author' => 'Автор',
    'Author ID' => 'ID автора',
    'Blog' => 'Блог',
    'Categories' => 'Категорії',
    'Category' => 'Категорія',
    'Category ID' => 'ID категорії',
    'Comments' => 'Коментарі',
    'Content' => 'Контент',
    'Create' => 'Створити',
    'Create Category' => 'Створити категорію',
    'Create Comment' => 'Створити коммнтар',
    'Create Post' => 'Створити пост',
    'Create User' => 'Створити користувача',
    'Delete' => 'Видалити',
    'Draft' => 'Чернетка',
    'Email' => 'E-mail',
    'Home' => 'Головна',
    'ID' => 'ID',
    'Login' => 'Вхід',
    'Logout ({username})' => 'Вихід ({username})',
    'Moderate' => 'На модерації',
    'My Yii Blog' => 'Мій Yii Блог',
    'New Password' => 'Новий пароль',
    'Password' => 'Пароль',
    'Repassword' => 'Повторіть пароль',

    'Ocr >Optical Character Recognition'=>'Ocr >Оптичне розпізнавання тексту',
    'On-line services'=>'Онлайнові послуги',
    'Pid' => 'PID',
    'Please fill out the following fields to login:' => 'Будьте ласкаві, заповніть ці поля для входу:',
    'Post ID' => 'ID поста',
    'Posts' => 'Пости',
    'Publish' => 'Опублікувати',
    'Publish Date' => 'Дата публікації',
    'Publish Status' => 'Статус',
    'Published' => 'Опублікований',
    'Published on' => 'Опубліковано',
    'Last updated on' => 'Відредаговано',
    'Comments ' => 'Коментарів ',
    'Add comment' => 'Коментувати',
    'Permalink' => 'Постійне посилання',
    'Role' => 'Роль',
    'Select language'=>'Виберіть мову',
    'Site' => 'Сайт',
    'Status' => 'Статус',
    'Tag ID' => 'Тег ID',
    'Tags' => 'Теги',
    'Title' => 'Заголовок',
    'Update' => 'Оновити',
    'Update Category:' => 'Оновити категорію:',
    'Update Comment:' => 'Оновити комментар:',
    'Update Post:' => 'Оновити пост:',
    'Update User:' => 'Редактувати користувача:',
    'Username' => "Ім'я користувача",
    'username' => "Ім'я користувача",
    'rememberMe' => "Запам'ятати мене",
    'Users' => 'Користувачі',

//    'Blog' => 'Блог',
    'Body' => 'Повідомлення',
    'E-mail' => 'E-mail',
    'If you forgot your password you can' => 'Якщо забули пароль, то Ви можете',
    'reset it' => 'відновити його',
    'Name' => "Ім'я",
    'Registration and recovery' => 'Реєстрація і відновлення',
    'Registration' => 'Реєстрація',
    'Forgot your password?' => 'Забули пароль?',
    'The entrance through social networks' => 'Вхід через соцмережі',
    'Please fill out the following fields to register' => 'Будьте ласкаві! Заповніть ці поля',
    'Please choose your new password' => 'Будьте ласкаві! Наберіть Ваш новий пароль',
    'Please contact us if you think this is a server error. Thank you.' => 'Будьте ласкаві! Повідомте нас про цю помилку. Наперед вдячні.',
    'Please fill out the following fields to login' => 'Будьте ласкаві! Заповніть це поле для входу',
    'Please fill out the following fields to signup' => 'Будьте ласкаві! Заповніть це поле для реєстрації',
    'Please fill out your email. A link to reset password will be sent there.' => 'Будьте ласкаві! Заповніть E-mail. На нього ми відправимо посилання для поновлення паролю',
    'Request password reset' => 'Запит поновлення пароля',
    'Reset password' => 'Зкинути пароль',
    'Save' => 'Зберегти',
    'Send' => 'Відправити',
    'Subject' => 'Тема',
    'The above error occurred while the Web server was processing your request.' => 'Помилка серверу при обрабці Вашого запиту.',
    'This is the About page. You may modify the following file to customize its content' => 'Сторінка "Про мене". Вы можете її модифікувати тут: ',
    'Verification Code' => 'Код перевірки',
    'About' => 'Про мене',
    'Administration' => 'Адмін-панель',
//    'Author' => 'Автор',
//    'Blog' => 'Блог',
//    'Categories' => 'Категорії',
//    'Category' => 'Категорія',
    'Contact' => 'Контакти',
    'Cancel' => 'Відмова',
    'Feedback form' => "Форма зворотнього зв'язку",

    'Close' => 'Закрити',
    'Logout' => 'Вихід',
    'Register' => 'Реєстрація',

    'More' => 'Читати дальше',
//    'Posts' => 'Пости',
    'Posts Tagged with'=>'Пости з тегом',
//    'Publish' => 'Опублікований',
//    'Publish date' => 'Дата публикації',
    'Sign up' => 'Реєстрація',
    'Submit' => 'Відправити',
//    'Verification Code' => 'Код перевірки',


//     'ID' => 'ID',
//     'Title' => 'Заголовок',
//     'Content' => 'Зміст',
//     'Status' => 'Статус',
//     'Category ID' => 'ID категорії',
     'Viewed' => 'Переглядів',
     'Terms of use' => 'Умови використання',
     'Created At' => 'Створено',
     'Updated At' => 'Оновлено',
     'Image Url' => 'Малюнок',


];
