<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created at' => 'Створено',
    'Updated at' => 'Оновлено',
    'Announce' => 'Анонс',
    'Are you sure you want to delete this item?' => 'Ви бажаєте вилучити цей запис?',
    'Author' => 'Автор',
    'Author ID' => 'ID автора',
    'Blog' => 'Блог',
    'Categories' => 'Категорії',
    'Category' => 'Категорія',
    'Category ID' => 'ID категорії',
    'Comments' => 'Коментарі',
    'Content' => 'Контент',
    'Create' => 'Створити',
    'Create Category' => 'Створити категорію',
    'Create Comment' => 'Створити коммнтар',
    'Create Post' => 'Створити пост',
    'Create User' => 'Створити користувача',
    'Delete' => 'Видалити',
    'Draft' => 'Чернетка',
    'Email' => 'E-mail',
    'Home' => 'Головна',
    'ID' => 'ID',
    'Login' => 'Вхіод',
    'Logout ({username})' => 'Вихід ({username})',
    'Moderate' => 'На модерації',
    'My Yii Blog' => 'Мой Yii Блог',
    'New Password' => 'Новий пароль',
    'Pid' => 'PID',
    'Please fill out the following fields to login:' => 'Будьте ласкаві, заповніть ці поля для входу:',
    'Post ID' => 'ID поста',
    'Posts' => 'Пости',
    'Publish' => 'Опублікувати',
    'Publish date' => 'Дата публікації',
    'Publish status' => 'Статус',
    'Published' => 'Опублікований',
    'Role' => 'Роль',
    'Site' => 'Сайт',
    'Status' => 'Статус',
    'Tag ID' => 'Тег ID',
    'Tags' => 'Теги',
    'Title' => 'Заголовок',
    'Update' => 'Обновити',
    'Update Category:' => 'Обновити категорію:',
    'Update Comment:' => 'Обновити комментар:',
    'Update Post:' => 'Обновити пост:',
    'Update User:' => 'Редактувати користувача:',
    'Username' => "Ім'я користувача",
    'Users' => 'Користувачі',
];
