<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Blog' => 'Блог',
    'Body' => 'Повідомлення',
    'E-mail' => 'E-mail',
    'If you forgot your password you can' => 'Якщо забули пароль, то Ви можете',
    'Name' => "Ім'я",
    'Please choose your new password' => 'Будьте ласкаві! Наберіть Ваш новий пароль',
    'Please contact us if you think this is a server error. Thank you.' => 'Будьте ласкаві! Повідомте нас про цю помилку. Наперед вдячні.',
    'Please fill out the following fields to login' => 'Будьте ласкаві! Заповніть це поле для входу',
    'Please fill out the following fields to signup' => 'Будьте ласкаві! Заповніть це поле для реєстрації',
    'Please fill out your email. A link to reset password will be sent there.' => 'Будьте ласкаві! Заповніть E-mail. На нього ми відправимо посилання для поновлення паролю',
    'Request password reset' => 'Запит поновлення пароля',
    'Reset password' => 'Зкинути пароль',
    'Save' => 'Зберегти',
    'Send' => 'Відправити',
    'Subject' => 'Тема',
    'The above error occurred while the Web server was processing your request.' => 'Помилка серверу при обрабці Вашого запиту.',
    'This is the About page. You may modify the following file to customize its content' => 'Сторінка "Про мене". Вы можете її модифікувати тут: ',
    'Verification Code' => 'Код перевірки',

    'About' => 'Про мене',
    'Administration' => 'Адмін-панель',
    'Author' => 'Автор',
    'Blog' => 'Блог',
    'Categories' => 'Категорії',
    'Category' => 'Категорія',
    'Contact' => 'Контакти',
    'Login' => 'Вхід',
    'Logout ({username})' => 'Вихід ({username})',
    'More' => 'Читати дальше',
    'Posts' => 'Пости',
    'Publish' => 'Опублікований',
    'Publish date' => 'Дата публикації',
    'Sign up' => 'Реєстрація',
    'Submit' => 'Відправити',
    'Tags' => 'Теги',
    'Posts Tagged with'=>'Пости з тегом',
    "A user with such an email as in {client} already exists, but is not connected with it. To get started, log on to the site using e-mail, in order to link it." =>
    "Користувач з такою електронною адресою як в {client} вже існує, проте с ним не повязаний. Зайдіть на сайт з використанням электронної пошти, для того, що б зв'язати її.",

];
